server:
  port: 8080
spring:
  application:
    name: timesheet-rest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  h2:
    console:
      enabled: true
#  регистрация eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

#  mvc:
#    cors:
#      mappings: "/**"
#      allowed-origins: "http://localhost:3000"
